#!/usr/bin/env python

# ebs - Evidence based scheduling program
# Copyright (C) 2011, 2012 Fraser Tweedale
# Copyright (C) 2011, 2012 Benon Technologies Pty Ltd
#
# ebs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import clilib

import ebslib
import ebslib.command
import ebslib.config

# retrieve config object
config = ebslib.config.Config.get_config('~/.ebsrc')

# create global arguments
global_args = [
    (['--version'],
    dict(action='version', version='%(prog)s {}'.format(ebslib.version))),
]

# create dispatcher
dispatcher = clilib.Dispatcher(
    global_args=global_args,
    with_config=True,
    config=config,
)

# add commands
for command in ebslib.command.commands:
    dispatcher.add_command(command)

# run
dispatcher.dispatch()
